apiVersion: v1
kind: Service
metadata:
  name: gs-spring-boot-docker
  namespace: integration
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: gs-spring-boot-docker