version: '3.8'

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    restart: always
    hostname: yky32.asuscomm.com  # Change to your domain or IP
    ports:
      - "8929:80"   # HTTP
      - "8922:22"   # SSH
    volumes:
      - gitlab-data:/var/opt/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-config:/etc/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://yky32.asuscomm.com:8929'  # Change to your domain or IP

volumes:
  gitlab-data:
  gitlab-logs:
  gitlab-config: