version: '3'
services:
  localstack:
    image: localstack/localstack:0.10.7
    container_name: localstack
    ports:
      - "4567-4593:4567-4593"
      - "${PORT_WEB_UI-8099}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=s3:4572,sqs:4573,sns:4574,ses:4575
      - DEFAULT_REGION=us-east-1
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=8080
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'

volumes:
  localstack-vol:
