version: '3'

services:
  postgres_name:
    container_name: name-of-db
    image: 'postgres:10.10-alpine'
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'name-of-db'
    volumes:
      - 'postgres_name:/var/lib/postgresql/data'
    ports:
      - '${POSTGRES_PORT:-5432}:5432'

volumes:
  postgres_name:
