version: "3"

services:
  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    ports:
      - '${REDIS_PORT:-6379}:6379'
    volumes:
      - 'redis_name:/data'

volumes:
  redis_name: